## Problem Statement

1. Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
n=7
res = np.column_stack([arr**(n-i-1) for i in range(n)])
print(res)

[[    1     1     1     1     1     1     1]
 [   64    32    16     8     4     2     1]
 [  729   243    81    27     9     3     1]
 [ 4096  1024   256    64    16     4     1]
 [15625  3125   625   125    25     5     1]]


In [3]:
#similar matrix using np.vander function in numpy 
arr = np.array([1,2,3,4,5])
n=7
res = np.vander(arr,n,increasing=False)
print(res)

[[    1     1     1     1     1     1     1]
 [   64    32    16     8     4     2     1]
 [  729   243    81    27     9     3     1]
 [ 4096  1024   256    64    16     4     1]
 [15625  3125   625   125    25     5     1]]


2. Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: <br> The moving average sequence has n-k+1 elements as shown below. 

In [4]:
# The moving averages with k=4 of a ten-value sequence (n=10) is shown below
# i 1 2 3 4 5 6 7 8 9 10
# ===== == == == == == == == == == ==
# Input 10 20 30 40 50 60 70 80 90 100
# y1 25 = (10+20+30+40)/4
# y2 35 = (20+30+40+50)/4
# y3 45 = (30+40+50+60)/4
# y4 55 = (40+50+60+70)/4
# y5 65 = (50+60+70+80)/4
# y6 75 = (60+70+80+90)/4
# y7 85 = (70+80+90+100)/4
# Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3

In [5]:
def move_avg(lst,k): 
    seq=len(lst)-k+1
    outputs=[]
    for num in range(seq):
        output=sum(lst[num:num+k])/k
        outputs.append(output)
    return outputs, len(outputs) 

In [6]:
inp=[10,20,30,40,50,60,70,80,90,100]
out,l=move_avg(inp,4)
print(out,l)

[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0] 7


In [7]:
inp=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
out,l=move_avg(inp,3)
print(out,l)

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333] 11


In [8]:
#similar problem can be solved using np.cumsum() function in numpy
# np.cumsum returns the cumulative sum of the elements along a given axis.

def move_avg(lst,n):
    res = np.cumsum(lst,dtype=float)
    res[n:] = res[n:] - res[:-n]
    return res[n-1:]/n

In [65]:
lst = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
out = np.array(move_avg(lst,3)).round(2)
print(out)

[  5.     4.67   5.67   6.67   9.67  28.67  49.33  72.67  84.    93.33
 116.33]
